version: '3.8'

services:
    app:
        build: .
        ports:
            - '8080:8080'
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_USER: postgres
            DB_PASSWORD: password
            DB_NAME: merchmarket
        networks:
            - app_network

    db:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: merchmarket
        ports:
            - '5432:5432'
        networks:
            - app_network
        volumes:
            - postgres_data:/var/lib/postgresql/data

networks:
    app_network:

volumes:
    postgres_data:
